# Name of the server, displayed as the header of the page
# If this is empty, it won't display the header at the top of the page at all
serverName: CommandStar!

# Description of your server.
# HTML tags are supported.
# Leave empty to hide the Server Description panel
# Tip: The > operator lets you write multiline configuration without
#   worrying about quotes.
serverDescription: >
  <strong>Welcome!</strong><br/>
  Enter information about your server here!

# empty serverDescription example:
#serverDescription:

# --- Server Paths and Files ---
starbound:
  binPath: /opt/starbound/bin
  assetsPath: /opt/starbound/assets
  dataPath: /opt/starbound/bin/universe
  logFile: /opt/starbound/bin/starbound_server.log
  configFile: /opt/starbound/bin/starbound.config

# --- Windows paths ---
# Use something like this for Windows instead of the above lines
#
#starbound:
#  binPath: C:\Games\Steam\SteamApps\common\Starbound\win32
#  assetsPath: C:\Games\Steam\SteamApps\common\Starbound\assets
#  dataPath: C:\Games\Steam\SteamApps\common\Starbound\universe
#  logFile: C:\Games\Steam\SteamApps\common\Starbound\starbound_server.log
#  configFile: C:\Games\Steam\SteamApps\common\Starbound\starbound.config


# --- Features ---
# Toggle various features on and off
features:
  # WARNING: starbound server bug can cause crashes after enough time on linux
  # Recommend you leave this off unless you understand managing ulimit
  serverStatus: false
  activeSystems: true
  apiFooter: true

# --- Chat Ignores ---
# Ignore slash commands and Starlight admin channels by default
ignoreChatPrefixes: "/#"

# --- Web Server Port ---
# If you use port 80, you'll need to run runServer.sh as sudo.
# This isn't super secure right now so be warned.
listenPort: 8080

# Number of chat messages to keep in memory
maxRecentChatMessages: 100


# --- Server Status ---

serverStatus:
  # how often to check server status, in seconds
  # WARNING: At least on Ubuntu, the starbound server leaks socket file
  # descriptors. This can crash the server after enough time.
  # You can increase the file limit of your starbound server with ulimit to
  # extend the time to crash.
  checkFrequency: 300

# --- Custom CSS ---
# list of additional CSS files to load
# These must live in public/css/
# They are loaded dynamically after the DOM has loaded so things might flash.
# Additional files must have the - before them, this is a YAML array
customCss:
  - bootstrap-theme.min.css

# Multiple CSS files should follow this format:
#customCss:
#  - theme1.css
#  - theme2.css

# --- HipChat ---
# To enable, you'll need to set the hipchat.token configuration to your API key
# This is only for relaying in-game chat to a HipChat room.  The web chat
# works without this.
# This REQUIRES a version 1 token
# For more info, check out their website: https://www.hipchat.com/

hipchat:
  token:
  # This room must already exist!
  room: Starbound
  user: Server
  color: yellow
  notify: false

# --- IRC ---
# If you uncomment the IRC block or put it in your server-specific config,
# CommandStar will attempt to connect to that server/channel and relay in-game
# messages to IRC.
# Very early code without hooks into all the configuration possible.  Please
# let me know if you need deeper functionality.
# More docs on the IRC module at
# https://node-irc.readthedocs.org/en/latest/index.html

#irc:
#  server:
#  nick: "StarboundBot"
#  channel: "#starbound"
#  user:
#  password:

datastore:
  dataPath: ./data
